'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.Sac.Admin
    
    Partial Public Class PazienteDettaglio
        
        '''<summary>
        '''LabelError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ToolbarTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolbarTable As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''ModificaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ModificaLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''MergeLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MergeLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''MergeDettaglioLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MergeDettaglioLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''RinotificaPazienteAttivoButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RinotificaPazienteAttivoButton As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''RinotificaFusioneButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RinotificaFusioneButton As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''EliminaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EliminaLink As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''RipristinaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RipristinaLink As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''VisualizzaLogLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VisualizzaLogLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''CopiaSuAppuntiLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CopiaSuAppuntiLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''SincronizzaLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SincronizzaLink As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''AnonimizzazioneLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AnonimizzazioneLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''PosizioneCollegataLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PosizioneCollegataLink As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''NomePazienteFormView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NomePazienteFormView As Global.System.Web.UI.WebControls.FormView
        
        '''<summary>
        '''TabContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabContainer As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''btnActiveViewAnagrafeStati control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewAnagrafeStati As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewResidenzaDomicilio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewResidenzaDomicilio As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewAssistitoMedicoBase control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewAssistitoMedicoBase As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewSTP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewSTP As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewEsenzioni control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewEsenzioni As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewConsensi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewConsensi As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewAnonimizzazioni control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewAnonimizzazioni As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnActiveViewPosizioniCollegate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActiveViewPosizioniCollegate As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''TabSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabSeparator As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''PazienteDettaglioFormView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PazienteDettaglioFormView As Global.System.Web.UI.WebControls.FormView
        
        '''<summary>
        '''PazienteDettaglioObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PazienteDettaglioObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''ComboNazioniObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ComboNazioniObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''ComboRegioniObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ComboRegioniObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''ComboPosizioniAssObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ComboPosizioniAssObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''MainScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainScriptManager As Global.AjaxControlToolkit.ToolkitScriptManager
    End Class
End Namespace
