'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WcfSacRoleManager
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GruppiReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GruppiReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GruppiField As WcfSacRoleManager.GruppiListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Gruppi() As WcfSacRoleManager.GruppiListaType
            Get
                Return Me.GruppiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GruppiField, value) <> true) Then
                    Me.GruppiField = value
                    Me.RaisePropertyChanged("Gruppi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ErroreType", [Namespace]:="http://schemas.progel.it/WCF/SAC/Types/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ErroreType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="GruppiListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="Gruppo"),  _
     System.SerializableAttribute()>  _
    Public Class GruppiListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.GruppoType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GruppoType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GruppoType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As String
        
        Private NomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        Private AttivoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property Attivo() As Boolean
            Get
                Return Me.AttivoField
            End Get
            Set
                If (Me.AttivoField.Equals(value) <> true) Then
                    Me.AttivoField = value
                    Me.RaisePropertyChanged("Attivo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GruppoReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GruppoReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GruppoField As WcfSacRoleManager.GruppoType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Gruppo() As WcfSacRoleManager.GruppoType
            Get
                Return Me.GruppoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GruppoField, value) <> true) Then
                    Me.GruppoField = value
                    Me.RaisePropertyChanged("Gruppo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RuoliReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RuoliReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RuoliField As WcfSacRoleManager.RuoliListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Ruoli() As WcfSacRoleManager.RuoliListaType
            Get
                Return Me.RuoliField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RuoliField, value) <> true) Then
                    Me.RuoliField = value
                    Me.RaisePropertyChanged("Ruoli")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="RuoliListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="Ruolo"),  _
     System.SerializableAttribute()>  _
    Public Class RuoliListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.RuoloType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RuoloType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RuoloType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As String
        
        Private CodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        Private AttivoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Attivo() As Boolean
            Get
                Return Me.AttivoField
            End Get
            Set
                If (Me.AttivoField.Equals(value) <> true) Then
                    Me.AttivoField = value
                    Me.RaisePropertyChanged("Attivo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RuoloDettagliReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RuoloDettagliReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RuoloDettaglioField As WcfSacRoleManager.RuoloDettagliType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property RuoloDettaglio() As WcfSacRoleManager.RuoloDettagliType
            Get
                Return Me.RuoloDettaglioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RuoloDettaglioField, value) <> true) Then
                    Me.RuoloDettaglioField = value
                    Me.RaisePropertyChanged("RuoloDettaglio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RuoloDettagliType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RuoloDettagliType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private RuoloField As WcfSacRoleManager.RuoloType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SistemiField As WcfSacRoleManager.SistemiListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitaOperativeField As WcfSacRoleManager.UnitaOperativeListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccessiField As WcfSacRoleManager.AccessiListaType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Ruolo() As WcfSacRoleManager.RuoloType
            Get
                Return Me.RuoloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RuoloField, value) <> true) Then
                    Me.RuoloField = value
                    Me.RaisePropertyChanged("Ruolo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Sistemi() As WcfSacRoleManager.SistemiListaType
            Get
                Return Me.SistemiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SistemiField, value) <> true) Then
                    Me.SistemiField = value
                    Me.RaisePropertyChanged("Sistemi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property UnitaOperative() As WcfSacRoleManager.UnitaOperativeListaType
            Get
                Return Me.UnitaOperativeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UnitaOperativeField, value) <> true) Then
                    Me.UnitaOperativeField = value
                    Me.RaisePropertyChanged("UnitaOperative")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Accessi() As WcfSacRoleManager.AccessiListaType
            Get
                Return Me.AccessiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccessiField, value) <> true) Then
                    Me.AccessiField = value
                    Me.RaisePropertyChanged("Accessi")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="SistemiListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="Sistema"),  _
     System.SerializableAttribute()>  _
    Public Class SistemiListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.SistemaType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="UnitaOperativeListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="UnitaOperativa"),  _
     System.SerializableAttribute()>  _
    Public Class UnitaOperativeListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.UnitaOperativaType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="AccessiListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="Accesso"),  _
     System.SerializableAttribute()>  _
    Public Class AccessiListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.AccessoType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SistemaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SistemaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As String
        
        Private CodiceField As String
        
        Private CodiceAziendaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        Private EroganteField As Boolean
        
        Private RichiedenteField As Boolean
        
        Private AttivoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=2)>  _
        Public Property CodiceAzienda() As String
            Get
                Return Me.CodiceAziendaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceAziendaField, value) <> true) Then
                    Me.CodiceAziendaField = value
                    Me.RaisePropertyChanged("CodiceAzienda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property Erogante() As Boolean
            Get
                Return Me.EroganteField
            End Get
            Set
                If (Me.EroganteField.Equals(value) <> true) Then
                    Me.EroganteField = value
                    Me.RaisePropertyChanged("Erogante")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property Richiedente() As Boolean
            Get
                Return Me.RichiedenteField
            End Get
            Set
                If (Me.RichiedenteField.Equals(value) <> true) Then
                    Me.RichiedenteField = value
                    Me.RaisePropertyChanged("Richiedente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property Attivo() As Boolean
            Get
                Return Me.AttivoField
            End Get
            Set
                If (Me.AttivoField.Equals(value) <> true) Then
                    Me.AttivoField = value
                    Me.RaisePropertyChanged("Attivo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnitaOperativaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UnitaOperativaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As String
        
        Private CodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        Private CodiceAziendaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttivoField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegimiField As WcfSacRoleManager.RegimiListaType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=3)>  _
        Public Property CodiceAzienda() As String
            Get
                Return Me.CodiceAziendaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceAziendaField, value) <> true) Then
                    Me.CodiceAziendaField = value
                    Me.RaisePropertyChanged("CodiceAzienda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property Attivo() As System.Nullable(Of Boolean)
            Get
                Return Me.AttivoField
            End Get
            Set
                If (Me.AttivoField.Equals(value) <> true) Then
                    Me.AttivoField = value
                    Me.RaisePropertyChanged("Attivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Regimi() As WcfSacRoleManager.RegimiListaType
            Get
                Return Me.RegimiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegimiField, value) <> true) Then
                    Me.RegimiField = value
                    Me.RaisePropertyChanged("Regimi")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="RegimiListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="Regime"),  _
     System.SerializableAttribute()>  _
    Public Class RegimiListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.CodiceDescrizioneType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CodiceDescrizioneType", [Namespace]:="http://schemas.progel.it/WCF/SAC/Types/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CodiceDescrizioneType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AccessoType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AccessoType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodiceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SistemiReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SistemiReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SistemiField As WcfSacRoleManager.SistemiListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Sistemi() As WcfSacRoleManager.SistemiListaType
            Get
                Return Me.SistemiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SistemiField, value) <> true) Then
                    Me.SistemiField = value
                    Me.RaisePropertyChanged("Sistemi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UnitaOperativeReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UnitaOperativeReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnitaOperativeField As WcfSacRoleManager.UnitaOperativeListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property UnitaOperative() As WcfSacRoleManager.UnitaOperativeListaType
            Get
                Return Me.UnitaOperativeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UnitaOperativeField, value) <> true) Then
                    Me.UnitaOperativeField = value
                    Me.RaisePropertyChanged("UnitaOperative")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UtentiReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UtentiReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UtentiField As WcfSacRoleManager.UtentiListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Utenti() As WcfSacRoleManager.UtentiListaType
            Get
                Return Me.UtentiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UtentiField, value) <> true) Then
                    Me.UtentiField = value
                    Me.RaisePropertyChanged("Utenti")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="UtentiListaType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0", ItemName:="Utente"),  _
     System.SerializableAttribute()>  _
    Public Class UtentiListaType
        Inherits System.Collections.Generic.List(Of WcfSacRoleManager.UtenteType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UtenteType", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UtenteType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As String
        
        Private UtenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CognomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodiceFiscaleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MatricolaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        Private AttivoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Utente() As String
            Get
                Return Me.UtenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UtenteField, value) <> true) Then
                    Me.UtenteField = value
                    Me.RaisePropertyChanged("Utente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Cognome() As String
            Get
                Return Me.CognomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CognomeField, value) <> true) Then
                    Me.CognomeField = value
                    Me.RaisePropertyChanged("Cognome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property CodiceFiscale() As String
            Get
                Return Me.CodiceFiscaleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceFiscaleField, value) <> true) Then
                    Me.CodiceFiscaleField = value
                    Me.RaisePropertyChanged("CodiceFiscale")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Matricola() As String
            Get
                Return Me.MatricolaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MatricolaField, value) <> true) Then
                    Me.MatricolaField = value
                    Me.RaisePropertyChanged("Matricola")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property Attivo() As Boolean
            Get
                Return Me.AttivoField
            End Get
            Set
                If (Me.AttivoField.Equals(value) <> true) Then
                    Me.AttivoField = value
                    Me.RaisePropertyChanged("Attivo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UtenteReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UtenteReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UtenteField As WcfSacRoleManager.UtenteType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Utente() As WcfSacRoleManager.UtenteType
            Get
                Return Me.UtenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UtenteField, value) <> true) Then
                    Me.UtenteField = value
                    Me.RaisePropertyChanged("Utente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AccessiReturn", [Namespace]:="http://schemas.progel.it/WCF/SAC/RoleManagerTypes/3.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AccessiReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AccessiField As WcfSacRoleManager.AccessiListaType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As WcfSacRoleManager.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Accessi() As WcfSacRoleManager.AccessiListaType
            Get
                Return Me.AccessiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AccessiField, value) <> true) Then
                    Me.AccessiField = value
                    Me.RaisePropertyChanged("Accessi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Errore() As WcfSacRoleManager.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.progel.it/WCF/SAC/Service/3.0", ConfigurationName:="WcfSacRoleManager.IRoleManager")>  _
    Public Interface IRoleManager
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiCercaResponse")>  _
        Function GruppiCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Gruppo As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.GruppiReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiCercaResponse")>  _
        Function GruppiCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Gruppo As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.GruppiReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppoOttieniPerNomeGru"& _ 
            "ppo", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppoOttieniPerNomeGru"& _ 
            "ppoResponse")>  _
        Function GruppoOttieniPerNomeGruppo(ByVal NomeGruppo As String) As WcfSacRoleManager.GruppoReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppoOttieniPerNomeGru"& _ 
            "ppo", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppoOttieniPerNomeGru"& _ 
            "ppoResponse")>  _
        Function GruppoOttieniPerNomeGruppoAsync(ByVal NomeGruppo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.GruppoReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiOttieniPerUtente", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiOttieniPerUtenteR"& _ 
            "esponse")>  _
        Function GruppiOttieniPerUtente(ByVal Utente As String) As WcfSacRoleManager.GruppiReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiOttieniPerUtente", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/GruppiOttieniPerUtenteR"& _ 
            "esponse")>  _
        Function GruppiOttieniPerUtenteAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.GruppiReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliCercaResponse")>  _
        Function RuoliCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.RuoliReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliCercaResponse")>  _
        Function RuoliCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerUtente", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerUtenteRe"& _ 
            "sponse")>  _
        Function RuoliOttieniPerUtente(ByVal Utente As String) As WcfSacRoleManager.RuoliReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerUtente", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerUtenteRe"& _ 
            "sponse")>  _
        Function RuoliOttieniPerUtenteAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerIdUtente"& _ 
            "", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerIdUtente"& _ 
            "Response")>  _
        Function RuoliOttieniPerIdUtente(ByVal IdUtente As System.Guid) As WcfSacRoleManager.RuoliReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerIdUtente"& _ 
            "", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerIdUtente"& _ 
            "Response")>  _
        Function RuoliOttieniPerIdUtenteAsync(ByVal IdUtente As System.Guid) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoloDettagliOttieni", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoloDettagliOttieniRes"& _ 
            "ponse")>  _
        Function RuoloDettagliOttieni(ByVal Utente As String, ByVal CodiceRuolo As String) As WcfSacRoleManager.RuoloDettagliReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoloDettagliOttieni", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoloDettagliOttieniRes"& _ 
            "ponse")>  _
        Function RuoloDettagliOttieniAsync(ByVal Utente As String, ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoloDettagliReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/SistemiCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/SistemiCercaResponse")>  _
        Function SistemiCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Erogante As System.Nullable(Of Boolean), ByVal Richiedente As System.Nullable(Of Boolean), ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.SistemiReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/SistemiCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/SistemiCercaResponse")>  _
        Function SistemiCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Erogante As System.Nullable(Of Boolean), ByVal Richiedente As System.Nullable(Of Boolean), ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.SistemiReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UnitaOperativeCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UnitaOperativeCercaResp"& _ 
            "onse")>  _
        Function UnitaOperativeCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.UnitaOperativeReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UnitaOperativeCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UnitaOperativeCercaResp"& _ 
            "onse")>  _
        Function UnitaOperativeCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UnitaOperativeReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiCercaResponse")>  _
        Function UtentiCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Utente As String, ByVal Descrizione As String, ByVal Cognome As String, ByVal Nome As String, ByVal CodiceFiscale As String, ByVal Matricola As String, ByVal Email As String, ByVal Attivo As System.Nullable(Of Boolean), ByVal CodiceRuolo As String) As WcfSacRoleManager.UtentiReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiCerca", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiCercaResponse")>  _
        Function UtentiCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Utente As String, ByVal Descrizione As String, ByVal Cognome As String, ByVal Nome As String, ByVal CodiceFiscale As String, ByVal Matricola As String, ByVal Email As String, ByVal Attivo As System.Nullable(Of Boolean), ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UtentiReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtenteOttieniPerNomeUte"& _ 
            "nte", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtenteOttieniPerNomeUte"& _ 
            "nteResponse")>  _
        Function UtenteOttieniPerNomeUtente(ByVal Utente As String) As WcfSacRoleManager.UtenteReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtenteOttieniPerNomeUte"& _ 
            "nte", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtenteOttieniPerNomeUte"& _ 
            "nteResponse")>  _
        Function UtenteOttieniPerNomeUtenteAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UtenteReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiOttieniPerRuolo", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiOttieniPerRuoloRe"& _ 
            "sponse")>  _
        Function UtentiOttieniPerRuolo(ByVal CodiceRuolo As String) As WcfSacRoleManager.UtentiReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiOttieniPerRuolo", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/UtentiOttieniPerRuoloRe"& _ 
            "sponse")>  _
        Function UtentiOttieniPerRuoloAsync(ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UtentiReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/AccessiOttieniPerRuolo", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/AccessiOttieniPerRuoloR"& _ 
            "esponse")>  _
        Function AccessiOttieniPerRuolo(ByVal CodiceRuolo As String) As WcfSacRoleManager.AccessiReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/AccessiOttieniPerRuolo", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/AccessiOttieniPerRuoloR"& _ 
            "esponse")>  _
        Function AccessiOttieniPerRuoloAsync(ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.AccessiReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerAttribut"& _ 
            "o", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerAttribut"& _ 
            "oResponse")>  _
        Function RuoliOttieniPerAttributo(ByVal Utente As String) As WcfSacRoleManager.RuoliReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerAttribut"& _ 
            "o", ReplyAction:="http://schemas.progel.it/WCF/SAC/Service/3.0/IRoleManager/RuoliOttieniPerAttribut"& _ 
            "oResponse")>  _
        Function RuoliOttieniPerAttributoAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IRoleManagerChannel
        Inherits WcfSacRoleManager.IRoleManager, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RoleManagerClient
        Inherits System.ServiceModel.ClientBase(Of WcfSacRoleManager.IRoleManager)
        Implements WcfSacRoleManager.IRoleManager
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GruppiCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Gruppo As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.GruppiReturn Implements WcfSacRoleManager.IRoleManager.GruppiCerca
            Return MyBase.Channel.GruppiCerca(MaxRecord, Ordinamento, Gruppo, Descrizione, Attivo)
        End Function
        
        Public Function GruppiCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Gruppo As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.GruppiReturn) Implements WcfSacRoleManager.IRoleManager.GruppiCercaAsync
            Return MyBase.Channel.GruppiCercaAsync(MaxRecord, Ordinamento, Gruppo, Descrizione, Attivo)
        End Function
        
        Public Function GruppoOttieniPerNomeGruppo(ByVal NomeGruppo As String) As WcfSacRoleManager.GruppoReturn Implements WcfSacRoleManager.IRoleManager.GruppoOttieniPerNomeGruppo
            Return MyBase.Channel.GruppoOttieniPerNomeGruppo(NomeGruppo)
        End Function
        
        Public Function GruppoOttieniPerNomeGruppoAsync(ByVal NomeGruppo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.GruppoReturn) Implements WcfSacRoleManager.IRoleManager.GruppoOttieniPerNomeGruppoAsync
            Return MyBase.Channel.GruppoOttieniPerNomeGruppoAsync(NomeGruppo)
        End Function
        
        Public Function GruppiOttieniPerUtente(ByVal Utente As String) As WcfSacRoleManager.GruppiReturn Implements WcfSacRoleManager.IRoleManager.GruppiOttieniPerUtente
            Return MyBase.Channel.GruppiOttieniPerUtente(Utente)
        End Function
        
        Public Function GruppiOttieniPerUtenteAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.GruppiReturn) Implements WcfSacRoleManager.IRoleManager.GruppiOttieniPerUtenteAsync
            Return MyBase.Channel.GruppiOttieniPerUtenteAsync(Utente)
        End Function
        
        Public Function RuoliCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.RuoliReturn Implements WcfSacRoleManager.IRoleManager.RuoliCerca
            Return MyBase.Channel.RuoliCerca(MaxRecord, Ordinamento, Codice, Descrizione, Attivo)
        End Function
        
        Public Function RuoliCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn) Implements WcfSacRoleManager.IRoleManager.RuoliCercaAsync
            Return MyBase.Channel.RuoliCercaAsync(MaxRecord, Ordinamento, Codice, Descrizione, Attivo)
        End Function
        
        Public Function RuoliOttieniPerUtente(ByVal Utente As String) As WcfSacRoleManager.RuoliReturn Implements WcfSacRoleManager.IRoleManager.RuoliOttieniPerUtente
            Return MyBase.Channel.RuoliOttieniPerUtente(Utente)
        End Function
        
        Public Function RuoliOttieniPerUtenteAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn) Implements WcfSacRoleManager.IRoleManager.RuoliOttieniPerUtenteAsync
            Return MyBase.Channel.RuoliOttieniPerUtenteAsync(Utente)
        End Function
        
        Public Function RuoliOttieniPerIdUtente(ByVal IdUtente As System.Guid) As WcfSacRoleManager.RuoliReturn Implements WcfSacRoleManager.IRoleManager.RuoliOttieniPerIdUtente
            Return MyBase.Channel.RuoliOttieniPerIdUtente(IdUtente)
        End Function
        
        Public Function RuoliOttieniPerIdUtenteAsync(ByVal IdUtente As System.Guid) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn) Implements WcfSacRoleManager.IRoleManager.RuoliOttieniPerIdUtenteAsync
            Return MyBase.Channel.RuoliOttieniPerIdUtenteAsync(IdUtente)
        End Function
        
        Public Function RuoloDettagliOttieni(ByVal Utente As String, ByVal CodiceRuolo As String) As WcfSacRoleManager.RuoloDettagliReturn Implements WcfSacRoleManager.IRoleManager.RuoloDettagliOttieni
            Return MyBase.Channel.RuoloDettagliOttieni(Utente, CodiceRuolo)
        End Function
        
        Public Function RuoloDettagliOttieniAsync(ByVal Utente As String, ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoloDettagliReturn) Implements WcfSacRoleManager.IRoleManager.RuoloDettagliOttieniAsync
            Return MyBase.Channel.RuoloDettagliOttieniAsync(Utente, CodiceRuolo)
        End Function
        
        Public Function SistemiCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Erogante As System.Nullable(Of Boolean), ByVal Richiedente As System.Nullable(Of Boolean), ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.SistemiReturn Implements WcfSacRoleManager.IRoleManager.SistemiCerca
            Return MyBase.Channel.SistemiCerca(MaxRecord, Ordinamento, Codice, Descrizione, CodiceAzienda, Erogante, Richiedente, Attivo)
        End Function
        
        Public Function SistemiCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Erogante As System.Nullable(Of Boolean), ByVal Richiedente As System.Nullable(Of Boolean), ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.SistemiReturn) Implements WcfSacRoleManager.IRoleManager.SistemiCercaAsync
            Return MyBase.Channel.SistemiCercaAsync(MaxRecord, Ordinamento, Codice, Descrizione, CodiceAzienda, Erogante, Richiedente, Attivo)
        End Function
        
        Public Function UnitaOperativeCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Attivo As System.Nullable(Of Boolean)) As WcfSacRoleManager.UnitaOperativeReturn Implements WcfSacRoleManager.IRoleManager.UnitaOperativeCerca
            Return MyBase.Channel.UnitaOperativeCerca(MaxRecord, Ordinamento, Codice, Descrizione, CodiceAzienda, Attivo)
        End Function
        
        Public Function UnitaOperativeCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Codice As String, ByVal Descrizione As String, ByVal CodiceAzienda As String, ByVal Attivo As System.Nullable(Of Boolean)) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UnitaOperativeReturn) Implements WcfSacRoleManager.IRoleManager.UnitaOperativeCercaAsync
            Return MyBase.Channel.UnitaOperativeCercaAsync(MaxRecord, Ordinamento, Codice, Descrizione, CodiceAzienda, Attivo)
        End Function
        
        Public Function UtentiCerca(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Utente As String, ByVal Descrizione As String, ByVal Cognome As String, ByVal Nome As String, ByVal CodiceFiscale As String, ByVal Matricola As String, ByVal Email As String, ByVal Attivo As System.Nullable(Of Boolean), ByVal CodiceRuolo As String) As WcfSacRoleManager.UtentiReturn Implements WcfSacRoleManager.IRoleManager.UtentiCerca
            Return MyBase.Channel.UtentiCerca(MaxRecord, Ordinamento, Utente, Descrizione, Cognome, Nome, CodiceFiscale, Matricola, Email, Attivo, CodiceRuolo)
        End Function
        
        Public Function UtentiCercaAsync(ByVal MaxRecord As System.Nullable(Of Integer), ByVal Ordinamento As String, ByVal Utente As String, ByVal Descrizione As String, ByVal Cognome As String, ByVal Nome As String, ByVal CodiceFiscale As String, ByVal Matricola As String, ByVal Email As String, ByVal Attivo As System.Nullable(Of Boolean), ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UtentiReturn) Implements WcfSacRoleManager.IRoleManager.UtentiCercaAsync
            Return MyBase.Channel.UtentiCercaAsync(MaxRecord, Ordinamento, Utente, Descrizione, Cognome, Nome, CodiceFiscale, Matricola, Email, Attivo, CodiceRuolo)
        End Function
        
        Public Function UtenteOttieniPerNomeUtente(ByVal Utente As String) As WcfSacRoleManager.UtenteReturn Implements WcfSacRoleManager.IRoleManager.UtenteOttieniPerNomeUtente
            Return MyBase.Channel.UtenteOttieniPerNomeUtente(Utente)
        End Function
        
        Public Function UtenteOttieniPerNomeUtenteAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UtenteReturn) Implements WcfSacRoleManager.IRoleManager.UtenteOttieniPerNomeUtenteAsync
            Return MyBase.Channel.UtenteOttieniPerNomeUtenteAsync(Utente)
        End Function
        
        Public Function UtentiOttieniPerRuolo(ByVal CodiceRuolo As String) As WcfSacRoleManager.UtentiReturn Implements WcfSacRoleManager.IRoleManager.UtentiOttieniPerRuolo
            Return MyBase.Channel.UtentiOttieniPerRuolo(CodiceRuolo)
        End Function
        
        Public Function UtentiOttieniPerRuoloAsync(ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.UtentiReturn) Implements WcfSacRoleManager.IRoleManager.UtentiOttieniPerRuoloAsync
            Return MyBase.Channel.UtentiOttieniPerRuoloAsync(CodiceRuolo)
        End Function
        
        Public Function AccessiOttieniPerRuolo(ByVal CodiceRuolo As String) As WcfSacRoleManager.AccessiReturn Implements WcfSacRoleManager.IRoleManager.AccessiOttieniPerRuolo
            Return MyBase.Channel.AccessiOttieniPerRuolo(CodiceRuolo)
        End Function
        
        Public Function AccessiOttieniPerRuoloAsync(ByVal CodiceRuolo As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.AccessiReturn) Implements WcfSacRoleManager.IRoleManager.AccessiOttieniPerRuoloAsync
            Return MyBase.Channel.AccessiOttieniPerRuoloAsync(CodiceRuolo)
        End Function
        
        Public Function RuoliOttieniPerAttributo(ByVal Utente As String) As WcfSacRoleManager.RuoliReturn Implements WcfSacRoleManager.IRoleManager.RuoliOttieniPerAttributo
            Return MyBase.Channel.RuoliOttieniPerAttributo(Utente)
        End Function
        
        Public Function RuoliOttieniPerAttributoAsync(ByVal Utente As String) As System.Threading.Tasks.Task(Of WcfSacRoleManager.RuoliReturn) Implements WcfSacRoleManager.IRoleManager.RuoliOttieniPerAttributoAsync
            Return MyBase.Channel.RuoliOttieniPerAttributoAsync(Utente)
        End Function
    End Class
End Namespace
