'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.Sac.User
    
    Partial Public Class EsenzioneDettaglio
        
        '''<summary>
        '''ToolbarRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolbarRow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lnkIndietro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkIndietro As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''fvDettaglioEsenzione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fvDettaglioEsenzione As Global.System.Web.UI.WebControls.FormView
        
        '''<summary>
        '''odsDettaglioEsenzione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsDettaglioEsenzione As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As DI.Sac.User.Site1
            Get
                Return CType(MyBase.Master,DI.Sac.User.Site1)
            End Get
        End Property
    End Class
End Namespace
