'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FarmaPrincipiAttiviLista

	'''<summary>
	'''LabelError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pannelloFiltri control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pannelloFiltri As Global.System.Web.UI.HtmlControls.HtmlTable

	'''<summary>
	'''txtFiltriCodice control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFiltriCodice As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''reg1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents reg1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''txtFiltriDescrizione control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFiltriDescrizione As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFiltriATC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFiltriATC As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFiltriPrincipioAttivoBase control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFiltriPrincipioAttivoBase As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''butFiltriRicerca control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butFiltriRicerca As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''gvLista control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvLista As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''odsLista control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsLista As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
