-- =============================================
-- Author:		Alessandro Nostini
-- Create date: 2016-05-11
-- Description:	Ritorna gli attributi del paziente IdSac
-- =============================================
CREATE FUNCTION [dbo].[OttienePazienteAttributiPerIdSac]
(	
	@IdSac UNIQUEIDENTIFIER
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT Id AS IdPazientiBase, Attributi.ANome AS Nome, Attributi.AValore AS Valore
	FROM 
	 	 (SELECT Id
				,CAST([Provenienza] AS SQL_VARIANT) AS [Provenienza]
				,CAST([IdProvenienza] AS SQL_VARIANT) AS [IdProvenienza]
				,CAST([DataInserimento] AS SQL_VARIANT) AS [DataInserimento]
				,CAST([DataModifica] AS SQL_VARIANT) AS [DataModifica]
				,CAST([Occultato] AS SQL_VARIANT) AS [Occultato]
				,CAST([Disattivato] AS SQL_VARIANT) AS [Disattivato]
				,CAST([Tessera] AS SQL_VARIANT) AS [Tessera]
				,CAST([Cognome] AS SQL_VARIANT) AS [Cognome]
				,CAST([Nome] AS SQL_VARIANT) AS [Nome]
				,CAST([DataNascita] AS SQL_VARIANT) AS [DataNascita]
				,CAST([Sesso] AS SQL_VARIANT) AS [Sesso]
				,CAST([ComuneNascitaCodice] AS SQL_VARIANT) AS [ComuneNascitaCodice]
				,CAST([ComuneNascitaNome] AS SQL_VARIANT) AS [ComuneNascitaNome]
				,CAST([ProvinciaNascitaCodice] AS SQL_VARIANT) AS [ProvinciaNascitaCodice]
				,CAST([ProvinciaNascitaNome] AS SQL_VARIANT) AS [ProvinciaNascitaNome]
				,CAST([NazionalitaCodice] AS SQL_VARIANT) AS [NazionalitaCodice]
				,CAST([NazionalitaNome] AS SQL_VARIANT) AS [NazionalitaNome]
				,CAST([CodiceFiscale] AS SQL_VARIANT) AS [CodiceFiscale]
				,CAST(CAST([DatiAnamnestici] AS VARCHAR(8000)) AS SQL_VARIANT) AS [DatiAnamnestici]
				,CAST([MantenimentoPediatra] AS SQL_VARIANT) AS [MantenimentoPediatra]
				,CAST([CapoFamiglia] AS SQL_VARIANT) AS [CapoFamiglia]
				,CAST([Indigenza] AS SQL_VARIANT) AS [Indigenza]
				,CAST([CodiceTerminazione] AS SQL_VARIANT) AS [CodiceTerminazione]
				,CAST([DescrizioneTerminazione] AS SQL_VARIANT) AS [DescrizioneTerminazione]
				,CAST([ComuneResCodice] AS SQL_VARIANT) AS [ComuneResCodice]
				,CAST([ComuneResNome] AS SQL_VARIANT) AS [ComuneResNome]
				,CAST([ProvinciaResCodice] AS SQL_VARIANT) AS [ProvinciaResCodice]
				,CAST([ProvinciaResNome] AS SQL_VARIANT) AS [ProvinciaResNome]
				,CAST([SubComuneRes] AS SQL_VARIANT) AS [SubComuneRes]
				,CAST([IndirizzoRes] AS SQL_VARIANT) AS [IndirizzoRes]
				,CAST([LocalitaRes] AS SQL_VARIANT) AS [LocalitaRes]
				,CAST([CapRes] AS SQL_VARIANT) AS [CapRes]
				,CAST([DataDecorrenzaRes] AS SQL_VARIANT) AS [DataDecorrenzaRes]
				,CAST([ProvinciaAslResCodice] AS SQL_VARIANT) AS [ProvinciaAslResCodice]
				,CAST([ProvinciaAslResNome] AS SQL_VARIANT) AS [ProvinciaAslResNome]
				,CAST([ComuneAslResCodice] AS SQL_VARIANT) AS [ComuneAslResCodice]
				,CAST([AslResNome] AS SQL_VARIANT) AS [AslResNome]
				,CAST([CodiceAslRes] AS SQL_VARIANT) AS [CodiceAslRes]
				,CAST([RegioneResCodice] AS SQL_VARIANT) AS [RegioneResCodice]
				,CAST([RegioneResNome] AS SQL_VARIANT) AS [RegioneResNome]
				,CAST([ComuneDomCodice] AS SQL_VARIANT) AS [ComuneDomCodice]
				,CAST([ComuneDomNome] AS SQL_VARIANT) AS [ComuneDomNome]
				,CAST([ProvinciaDomCodice] AS SQL_VARIANT) AS [ProvinciaDomCodice]
				,CAST([ProvinciaDomNome] AS SQL_VARIANT) AS [ProvinciaDomNome]
				,CAST([SubComuneDom] AS SQL_VARIANT) AS [SubComuneDom]
				,CAST([IndirizzoDom] AS SQL_VARIANT) AS [IndirizzoDom]
				,CAST([LocalitaDom] AS SQL_VARIANT) AS [LocalitaDom]
				,CAST([CapDom] AS SQL_VARIANT) AS [CapDom]
				,CAST([PosizioneAss] AS SQL_VARIANT) AS [PosizioneAss]
				,CAST([RegioneAssCodice] AS SQL_VARIANT) AS [RegioneAssCodice]
				,CAST([RegioneAssNome] AS SQL_VARIANT) AS [RegioneAssNome]
				,CAST([ProvinciaAslAssCodice] AS SQL_VARIANT) AS [ProvinciaAslAssCodice]
				,CAST([ProvinciaAslAssNome] AS SQL_VARIANT) AS [ProvinciaAslAssNome]
				,CAST([ComuneAslAssCodice] AS SQL_VARIANT) AS [ComuneAslAssCodice]
				,CAST([AslAssNome] AS SQL_VARIANT) AS [AslAssNome]
				,CAST([CodiceAslAss] AS SQL_VARIANT) AS [CodiceAslAss]
				,CAST([DataInizioAss] AS SQL_VARIANT) AS [DataInizioAss]
				,CAST([DataScadenzaAss] AS SQL_VARIANT) AS [DataScadenzaAss]
				,CAST([DataTerminazioneAss] AS SQL_VARIANT) AS [DataTerminazioneAss]
				,CAST([DistrettoAmm] AS SQL_VARIANT) AS [DistrettoAmm]
				,CAST([DistrettoTer] AS SQL_VARIANT) AS [DistrettoTer]
				,CAST([Ambito] AS SQL_VARIANT) AS [Ambito]
				,CAST([CodiceMedicoDiBase] AS SQL_VARIANT) AS [CodiceMedicoDiBase]
				,CAST([CodiceFiscaleMedicoDiBase] AS SQL_VARIANT) AS [CodiceFiscaleMedicoDiBase]
				,CAST([CognomeNomeMedicoDiBase] AS SQL_VARIANT) AS [CognomeNomeMedicoDiBase]
				,CAST([DistrettoMedicoDiBase] AS SQL_VARIANT) AS [DistrettoMedicoDiBase]
				,CAST([DataSceltaMedicoDiBase] AS SQL_VARIANT) AS [DataSceltaMedicoDiBase]
				,CAST([ComuneRecapitoCodice] AS SQL_VARIANT) AS [ComuneRecapitoCodice]
				,CAST([ComuneRecapitoNome] AS SQL_VARIANT) AS [ComuneRecapitoNome]
				,CAST([ProvinciaRecapitoCodice] AS SQL_VARIANT) AS [ProvinciaRecapitoCodice]
				,CAST([ProvinciaRecapitoNome] AS SQL_VARIANT) AS [ProvinciaRecapitoNome]
				,CAST([IndirizzoRecapito] AS SQL_VARIANT) AS [IndirizzoRecapito]
				,CAST([LocalitaRecapito] AS SQL_VARIANT) AS [LocalitaRecapito]
				,CAST([Telefono1] AS SQL_VARIANT) AS [Telefono1]
				,CAST([Telefono2] AS SQL_VARIANT) AS [Telefono2]
				,CAST([Telefono3] AS SQL_VARIANT) AS [Telefono3]
				,CAST([CodiceSTP] AS SQL_VARIANT) AS [CodiceSTP]
				,CAST([DataInizioSTP] AS SQL_VARIANT) AS [DataInizioSTP]
				,CAST([DataFineSTP] AS SQL_VARIANT) AS [DataFineSTP]
				,CAST([MotivoAnnulloSTP] AS SQL_VARIANT) AS [MotivoAnnulloSTP]
				,CAST([FusioneId] AS SQL_VARIANT) AS [FusioneId]
				,CAST([FusioneProvenienza] AS SQL_VARIANT) AS [FusioneProvenienza]
				,CAST([FusioneIdProvenienza] AS SQL_VARIANT) AS [FusioneIdProvenienza]
				-- 2016-05-11 SAndro
				,CAST([DataDecesso] AS SQL_VARIANT) AS [DataDecesso]
				,CAST([ConsensoAziendaleCodice] AS SQL_VARIANT) AS [ConsensoAziendaleCodice]
				,CAST([ConsensoAziendaleDescrizione] AS SQL_VARIANT) AS [ConsensoAziendaleDescrizione]
				,CAST([ConsensoAziendaleData] AS SQL_VARIANT) AS [ConsensoAziendaleData]
				,CAST([ConsensoSoleCodice] AS SQL_VARIANT) AS [ConsensoSoleCodice]
				,CAST([ConsensoSoleDescrizione] AS SQL_VARIANT) AS [ConsensoSoleDescrizione]
				,CAST([ConsensoSoleData] AS SQL_VARIANT) AS [ConsensoSoleData]

			FROM dbo.SAC_Pazienti AS Pazienti WITH(NOLOCK)
 			WHERE Id = @IdSac
 				AND Id <> '00000000-0000-0000-0000-000000000000' 
			) Pazienti

	 UNPIVOT (AValore FOR ANome IN ( [Provenienza]
									,[IdProvenienza]
									,[DataInserimento]
									,[DataModifica]
									,[Occultato]
									,[Disattivato]
									,[Tessera]
									,[Cognome]
									,[Nome]
									,[DataNascita]
									,[Sesso]
									,[ComuneNascitaCodice]
									,[ComuneNascitaNome]
									,[ProvinciaNascitaCodice]
									,[ProvinciaNascitaNome]
									,[NazionalitaCodice]
									,[NazionalitaNome]
									,[CodiceFiscale]
									,[DatiAnamnestici]
									,[MantenimentoPediatra]
									,[CapoFamiglia]
									,[Indigenza]
									,[CodiceTerminazione]
									,[DescrizioneTerminazione]
									,[ComuneResCodice]
									,[ComuneResNome]
									,[ProvinciaResCodice]
									,[ProvinciaResNome]
									,[SubComuneRes]
									,[IndirizzoRes]
									,[LocalitaRes]
									,[CapRes]
									,[DataDecorrenzaRes]
									,[ProvinciaAslResCodice]
									,[ProvinciaAslResNome]
									,[ComuneAslResCodice]
									,[AslResNome]
									,[CodiceAslRes]
									,[RegioneResCodice]
									,[RegioneResNome]
									,[ComuneDomCodice]
									,[ComuneDomNome]
									,[ProvinciaDomCodice]
									,[ProvinciaDomNome]
									,[SubComuneDom]
									,[IndirizzoDom]
									,[LocalitaDom]
									,[CapDom]
									,[PosizioneAss]
									,[RegioneAssCodice]
									,[RegioneAssNome]
									,[ProvinciaAslAssCodice]
									,[ProvinciaAslAssNome]
									,[ComuneAslAssCodice]
									,[AslAssNome]
									,[CodiceAslAss]
									,[DataInizioAss]
									,[DataScadenzaAss]
									,[DataTerminazioneAss]
									,[DistrettoAmm]
									,[DistrettoTer]
									,[Ambito]
									,[CodiceMedicoDiBase]
									,[CodiceFiscaleMedicoDiBase]
									,[CognomeNomeMedicoDiBase]
									,[DistrettoMedicoDiBase]
									,[DataSceltaMedicoDiBase]
									,[ComuneRecapitoCodice]
									,[ComuneRecapitoNome]
									,[ProvinciaRecapitoCodice]
									,[ProvinciaRecapitoNome]
									,[IndirizzoRecapito]
									,[LocalitaRecapito]
									,[Telefono1]
									,[Telefono2]
									,[Telefono3]
									,[CodiceSTP]
									,[DataInizioSTP]
									,[DataFineSTP]
									,[MotivoAnnulloSTP]
									,[FusioneId]
									,[FusioneProvenienza]
									,[FusioneIdProvenienza]
									,[DataDecesso]
									,[ConsensoAziendaleCodice]
									,[ConsensoAziendaleDescrizione]
									,[ConsensoAziendaleData]
									,[ConsensoSoleCodice]
									,[ConsensoSoleDescrizione]
									,[ConsensoSoleData]
								)) AS Attributi
)