'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.DataWarehouse.Admin
    
    Partial Public Class FileUpload
        
        '''<summary>
        '''ErrorMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorMessageLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TitleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TitleLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''InfoLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InfoLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''FileLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''InputFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputFile As Global.System.Web.UI.HtmlControls.HtmlInputFile
        
        '''<summary>
        '''fv1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fv1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''OkButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OkButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''CancelButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
