'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OscuramentiRinotifica
    
    '''<summary>
    '''LabelError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''wizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizard As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnOkTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOkTop As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAnnullaTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnullaTop As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''OdsDettaglioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OdsDettaglioOscuramento As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''fvVecchioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvVecchioOscuramento As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''odsVecchioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsVecchioOscuramento As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gvListareferti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListareferti As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsReferti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsReferti As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''divRefertiOscuramentoOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRefertiOscuramentoOld As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvListaRefertiVecchioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListaRefertiVecchioOscuramento As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsRefertiVecchioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRefertiVecchioOscuramento As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsEventi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEventi As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''divEventiOscuramentoOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEventiOscuramentoOld As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvListaEventiVecchioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListaEventiVecchioOscuramento As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsEventiVecchioOscuramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsEventiVecchioOscuramento As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAnnulla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnulla As Global.System.Web.UI.WebControls.Button
End Class
