'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.DataWarehouse.Admin

    Partial Public Class RefertiNoteLista

        '''<summary>
        '''LabelError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''filterPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''NumeroRefertoTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NumeroRefertoTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''NosologicoTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NosologicoTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DataDalTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataDalTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DataAlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataAlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''VisualizzaNoteCancellateCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VisualizzaNoteCancellateCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CercaButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CercaButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''NoRecordFoundLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NoRecordFoundLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''GridViewMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewMain As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''DataSourceMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataSourceMain As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
