'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.DataWarehouse.Admin

    Partial Public Class SoleAbilitazioni

        '''<summary>
        '''filterPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''AziendaDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AziendaDropDownList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SistemaEroganteDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemaEroganteDropDownList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CercaButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CercaButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LabelError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''MainValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''AbilitazioniListView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AbilitazioniListView As Global.System.Web.UI.WebControls.ListView

        '''<summary>
        '''AbilitazioniObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AbilitazioniObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''AziendeObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AziendeObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''SistemaEroganteObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemaEroganteObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
