'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.DataWarehouse.Admin
    
    Partial Public Class TipiRefertoDettaglio
        
        '''<summary>
        '''LabelError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''labelTitolo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelTitolo As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cmbAziendaErogante control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbAziendaErogante As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''AziendeObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AziendeObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''ddlSistemaErogante control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSistemaErogante As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rv2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rv2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''FormViewDettaglio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormViewDettaglio As Global.System.Web.UI.WebControls.FormView
        
        '''<summary>
        '''odsDettaglio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsDettaglio As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''odsSistemiEroganti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsSistemiEroganti As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
