'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Step4

    '''<summary>
    '''UpdatePanelEsito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelEsito As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''DivSuccessi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSuccessi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LblPrestazioniCompletate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPrestazioniCompletate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DivFallite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivFallite As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LblPrestazioniFallite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPrestazioniFallite As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanelPrestazioniFallite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelPrestazioniFallite As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridViewPrestazioniFallite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewPrestazioniFallite As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BtnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnOk As Global.System.Web.UI.WebControls.Button
End Class
