<?xml version="1.0" encoding="utf-8"?><Database Name="AuslAsmnRe_DwhConnAnthema" Class="DwhConnAnthemaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=coruscant;Initial Catalog=AuslAsmnRe_DwhConnAnthema;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AuslAsmnRe_DwhConnAnthemaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CentriRichiedenti" Member="CentriRichiedenti">
    <Type Name="CentriRichiedenti">
      <Column Name="Nome" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Codice" Type="System.String" DbType="VarChar(64) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PuntoPrelievo" Type="System.String" DbType="VarChar(64) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CodiceLIS" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="AziendaErogante" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="SistemaErogante" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="AziendaRichiedente" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="SistemaRichiedente" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="PCInvioRichiesta" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="RepartoErogante" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="SezioneErogante" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="SpecialitaErogante" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
    </Type>
  </Table>
</Database>