<?xml version="1.0" encoding="utf-8"?><Database Name="Asmn_DwhOut_MedicinaNucleare" Class="DwhOutMedicinaNucleareDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ALDERAAN;Initial Catalog=Asmn_DwhOut_MedicinaNucleare;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Asmn_DwhOut_MedicinaNucleareConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PazientiDaMonitorare" Member="PazientiDaMonitorare">
    <Type Name="PazientiDaMonitorare">
      <Column Name="Id" AutoSync="Never" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataInizioMonitoraggio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataFineMonitoraggio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrestazioniDaMonitorare" Member="PrestazioniDaMonitorare">
    <Type Name="PrestazioniDaMonitorare">
      <Column Name="Codice" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>