<?xml version="1.0" encoding="utf-8"?><Database Name="AuslAsmnRe_OePlanner" EntityNamespace="OePlanner" ContextNamespace="OePlanner" Class="OePlannerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=alderaan;Initial Catalog=AuslAsmnRe_OePlanner;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AuslAsmnRe_OePlannerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sistemi" Member="Sistemi">
    <Type Name="Sistemi">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataInserimento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataModifica" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UtenteInserimento" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UtenteModifica" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Codice" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceAzienda" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Attivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Richiedente" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Erogante" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RichiedenteProgrammabile" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Regimi" Member="Regimis">
    <Type Name="Regimi">
      <Column Name="Codice" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Ordinamento" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Priorita" Member="Prioritas">
    <Type Name="Priorita">
      <Column Name="Codice" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Ordinamento" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>