'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OggettoADDettaglio

	'''<summary>
	'''LabelError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTitolo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitolo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Toolbar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Toolbar As Global.System.Web.UI.HtmlControls.HtmlTable

	'''<summary>
	'''lnkNuovo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkNuovo As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''FormViewDettaglio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FormViewDettaglio As Global.System.Web.UI.WebControls.FormView

	'''<summary>
	'''lblTitoloMembriGruppo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitoloMembriGruppo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''gvListaMembridelGruppo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvListaMembridelGruppo As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''gvListaGruppi control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvListaGruppi As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''butAnnulla control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butAnnulla As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''odsDettaglio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsDettaglio As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''odsMembriOttieniPerGruppo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsMembriOttieniPerGruppo As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''odsGruppiOttieniPerUtente control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsGruppiOttieniPerUtente As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
