'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.OrderEntry.Admin
    
    Partial Public Class OrdiniRichiesti
        
        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''filterPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''AnnoTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AnnoTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''NumeroTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NumeroTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''SistemaEroganteFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemaEroganteFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''StatoDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatoDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''PeriodoInserimentoDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PeriodoInserimentoDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''DataInserimentoDaTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataInserimentoDaTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''DataInserimentoATextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataInserimentoATextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''SistemaRichiedenteFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemaRichiedenteFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''IdRichiestaTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IdRichiestaTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''PeriodoRichiestaDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PeriodoRichiestaDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''UnitaOperativaRichiedenteTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitaOperativaRichiedenteTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''DataRichiestaDaTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataRichiestaDaTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''DataRichiestaATextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataRichiestaATextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''NosologicoTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NosologicoTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''NomeAnagraficaTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NomeAnagraficaTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''CodiceAnagraficaTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CodiceAnagraficaTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''CognomeTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CognomeTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''NomeTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NomeTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''DataNascitaTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataNascitaTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''CodiceFiscaleTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CodiceFiscaleTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''NumeroRisultatiDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NumeroRisultatiDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''SearchButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''ClearFilterButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ClearFilterButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''OrdiniGridView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrdiniGridView As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''OrdiniListaObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrdiniListaObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''SistemiErogantiObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemiErogantiObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''StatoObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatoObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''SistemiRichiedentiObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemiRichiedentiObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
