'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SacWcfServiceReferenceConsensi
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessaggioConsensoTipoEnum", [Namespace]:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0")>  _
    Public Enum MessaggioConsensoTipoEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Insert = 0
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessaggioConsensoParameter", [Namespace]:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessaggioConsensoParameter
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UtenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataSequenzaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConsensoField As SacWcfServiceReferenceConsensi.ConsensoType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Utente() As String
            Get
                Return Me.UtenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UtenteField, value) <> true) Then
                    Me.UtenteField = value
                    Me.RaisePropertyChanged("Utente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Property DataSequenza() As Date
            Get
                Return Me.DataSequenzaField
            End Get
            Set
                If (Me.DataSequenzaField.Equals(value) <> true) Then
                    Me.DataSequenzaField = value
                    Me.RaisePropertyChanged("DataSequenza")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Consenso() As SacWcfServiceReferenceConsensi.ConsensoType
            Get
                Return Me.ConsensoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConsensoField, value) <> true) Then
                    Me.ConsensoField = value
                    Me.RaisePropertyChanged("Consenso")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsensoType", [Namespace]:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ConsensoType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoField As String
        
        Private DataStatoField As Date
        
        Private StatoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperatoreIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperatoreCognomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperatoreNomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperatoreComputerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteProvenienzaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteIdProvenienzaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteCognomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteNomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteCodiceFiscaleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteDataNascitaField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteComuneNascitaCodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteNazionalitaCodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PazienteTesseraSanitariaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Tipo() As String
            Get
                Return Me.TipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoField, value) <> true) Then
                    Me.TipoField = value
                    Me.RaisePropertyChanged("Tipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property DataStato() As Date
            Get
                Return Me.DataStatoField
            End Get
            Set
                If (Me.DataStatoField.Equals(value) <> true) Then
                    Me.DataStatoField = value
                    Me.RaisePropertyChanged("DataStato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Stato() As Boolean
            Get
                Return Me.StatoField
            End Get
            Set
                If (Me.StatoField.Equals(value) <> true) Then
                    Me.StatoField = value
                    Me.RaisePropertyChanged("Stato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property OperatoreId() As String
            Get
                Return Me.OperatoreIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperatoreIdField, value) <> true) Then
                    Me.OperatoreIdField = value
                    Me.RaisePropertyChanged("OperatoreId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property OperatoreCognome() As String
            Get
                Return Me.OperatoreCognomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperatoreCognomeField, value) <> true) Then
                    Me.OperatoreCognomeField = value
                    Me.RaisePropertyChanged("OperatoreCognome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property OperatoreNome() As String
            Get
                Return Me.OperatoreNomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperatoreNomeField, value) <> true) Then
                    Me.OperatoreNomeField = value
                    Me.RaisePropertyChanged("OperatoreNome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property OperatoreComputer() As String
            Get
                Return Me.OperatoreComputerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperatoreComputerField, value) <> true) Then
                    Me.OperatoreComputerField = value
                    Me.RaisePropertyChanged("OperatoreComputer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property PazienteProvenienza() As String
            Get
                Return Me.PazienteProvenienzaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteProvenienzaField, value) <> true) Then
                    Me.PazienteProvenienzaField = value
                    Me.RaisePropertyChanged("PazienteProvenienza")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property PazienteIdProvenienza() As String
            Get
                Return Me.PazienteIdProvenienzaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteIdProvenienzaField, value) <> true) Then
                    Me.PazienteIdProvenienzaField = value
                    Me.RaisePropertyChanged("PazienteIdProvenienza")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property PazienteCognome() As String
            Get
                Return Me.PazienteCognomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteCognomeField, value) <> true) Then
                    Me.PazienteCognomeField = value
                    Me.RaisePropertyChanged("PazienteCognome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property PazienteNome() As String
            Get
                Return Me.PazienteNomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteNomeField, value) <> true) Then
                    Me.PazienteNomeField = value
                    Me.RaisePropertyChanged("PazienteNome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property PazienteCodiceFiscale() As String
            Get
                Return Me.PazienteCodiceFiscaleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteCodiceFiscaleField, value) <> true) Then
                    Me.PazienteCodiceFiscaleField = value
                    Me.RaisePropertyChanged("PazienteCodiceFiscale")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=13)>  _
        Public Property PazienteDataNascita() As System.Nullable(Of Date)
            Get
                Return Me.PazienteDataNascitaField
            End Get
            Set
                If (Me.PazienteDataNascitaField.Equals(value) <> true) Then
                    Me.PazienteDataNascitaField = value
                    Me.RaisePropertyChanged("PazienteDataNascita")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property PazienteComuneNascitaCodice() As String
            Get
                Return Me.PazienteComuneNascitaCodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteComuneNascitaCodiceField, value) <> true) Then
                    Me.PazienteComuneNascitaCodiceField = value
                    Me.RaisePropertyChanged("PazienteComuneNascitaCodice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property PazienteNazionalitaCodice() As String
            Get
                Return Me.PazienteNazionalitaCodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteNazionalitaCodiceField, value) <> true) Then
                    Me.PazienteNazionalitaCodiceField = value
                    Me.RaisePropertyChanged("PazienteNazionalitaCodice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property PazienteTesseraSanitaria() As String
            Get
                Return Me.PazienteTesseraSanitariaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PazienteTesseraSanitariaField, value) <> true) Then
                    Me.PazienteTesseraSanitariaField = value
                    Me.RaisePropertyChanged("PazienteTesseraSanitaria")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessaggioConsensoReturn", [Namespace]:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MessaggioConsensoReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErroreField As SacWcfServiceReferenceConsensi.ErroreType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Errore() As SacWcfServiceReferenceConsensi.ErroreType
            Get
                Return Me.ErroreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErroreField, value) <> true) Then
                    Me.ErroreField = value
                    Me.RaisePropertyChanged("Errore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ErroreType", [Namespace]:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ErroreType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescrizioneField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodiceField, value) <> true) Then
                    Me.CodiceField = value
                    Me.RaisePropertyChanged("Codice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescrizioneField, value) <> true) Then
                    Me.DescrizioneField = value
                    Me.RaisePropertyChanged("Descrizione")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0", ConfigurationName:="SacWcfServiceReferenceConsensi.IConsensi")>  _
    Public Interface IConsensi
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0/IConsensi/ProcessaMessaggio", ReplyAction:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0/IConsensi/ProcessaMessaggioResponse"& _ 
            "")>  _
        Function ProcessaMessaggio(ByVal Tipo As SacWcfServiceReferenceConsensi.MessaggioConsensoTipoEnum, ByVal Messaggio As SacWcfServiceReferenceConsensi.MessaggioConsensoParameter) As SacWcfServiceReferenceConsensi.MessaggioConsensoReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0/IConsensi/ProcessaMessaggio", ReplyAction:="http://SAC.BT.Consenso.Schema.DataAccess/v1.0/IConsensi/ProcessaMessaggioResponse"& _ 
            "")>  _
        Function ProcessaMessaggioAsync(ByVal Tipo As SacWcfServiceReferenceConsensi.MessaggioConsensoTipoEnum, ByVal Messaggio As SacWcfServiceReferenceConsensi.MessaggioConsensoParameter) As System.Threading.Tasks.Task(Of SacWcfServiceReferenceConsensi.MessaggioConsensoReturn)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IConsensiChannel
        Inherits SacWcfServiceReferenceConsensi.IConsensi, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsensiClient
        Inherits System.ServiceModel.ClientBase(Of SacWcfServiceReferenceConsensi.IConsensi)
        Implements SacWcfServiceReferenceConsensi.IConsensi
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ProcessaMessaggio(ByVal Tipo As SacWcfServiceReferenceConsensi.MessaggioConsensoTipoEnum, ByVal Messaggio As SacWcfServiceReferenceConsensi.MessaggioConsensoParameter) As SacWcfServiceReferenceConsensi.MessaggioConsensoReturn Implements SacWcfServiceReferenceConsensi.IConsensi.ProcessaMessaggio
            Return MyBase.Channel.ProcessaMessaggio(Tipo, Messaggio)
        End Function
        
        Public Function ProcessaMessaggioAsync(ByVal Tipo As SacWcfServiceReferenceConsensi.MessaggioConsensoTipoEnum, ByVal Messaggio As SacWcfServiceReferenceConsensi.MessaggioConsensoParameter) As System.Threading.Tasks.Task(Of SacWcfServiceReferenceConsensi.MessaggioConsensoReturn) Implements SacWcfServiceReferenceConsensi.IConsensi.ProcessaMessaggioAsync
            Return MyBase.Channel.ProcessaMessaggioAsync(Tipo, Messaggio)
        End Function
    End Class
End Namespace
