'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.PortalAdmin.Home
    
    Partial Public Class ReportViewer

		'''<summary>
		'''IframeMain control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents IframeMain As Global.System.Web.UI.HtmlControls.HtmlIframe
	End Class
End Namespace
