'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PazientiConsensoModifica

    '''<summary>
    '''BarraNavigazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavigazione As Global.DwhClinico.Web.NavigationBar

    '''<summary>
    '''PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUtenteNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUtenteNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCognome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataNascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLuogoNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLuogoNascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodiceFiscale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodiceFiscale As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboConsenso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboConsenso As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trUtenteAutorizzatoreTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUtenteAutorizzatoreTitle As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblUtenteAutorizzatoreTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUtenteAutorizzatoreTitolo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trUtenteAutorizzatoreRelazioneColMinore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUtenteAutorizzatoreRelazioneColMinore As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''cmbAutorizzatoreMinoreRelazioneColMinore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAutorizzatoreMinoreRelazioneColMinore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trUtenteAutorizzatoreCognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUtenteAutorizzatoreCognome As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtAutorizzatoreMinoreCognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutorizzatoreMinoreCognome As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqAutorizzatoreMinoreCognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqAutorizzatoreMinoreCognome As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trUtenteAutorizzatoreNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUtenteAutorizzatoreNome As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtAutorizzatoreMinoreNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutorizzatoreMinoreNome As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqAutorizzatoreMinoreNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqAutorizzatoreMinoreNome As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trUtenteAutorizzatoreDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUtenteAutorizzatoreDataNascita As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtAutorizzatoreDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutorizzatoreDataNascita As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqAutorizzatoreDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqAutorizzatoreDataNascita As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangeValAutorizzatoreDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValAutorizzatoreDataNascita As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''trUtenteAutorizzatoreLuogoNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trUtenteAutorizzatoreLuogoNascita As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtAutorizzatoreLuogoNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutorizzatoreLuogoNascita As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqAutorizzatoreLuogoNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqAutorizzatoreLuogoNascita As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cmdOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdAnnulla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAnnulla As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''cmdInformativa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdInformativa As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
