'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.OrderEntry.Admin
    
    Partial Public Class Ennuple
        
        '''<summary>
        '''filterPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''NotFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''GruppoUtentiFiltroTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GruppoUtentiFiltroTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''UnitaOperativaFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitaOperativaFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''DescrizioneFiltroTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DescrizioneFiltroTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''StatoFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatoFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''GruppoPrestazioniFiltroTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GruppoPrestazioniFiltroTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''SistemaRichiedenteFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemaRichiedenteFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''RegimeFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegimeFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''PrioritaFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrioritaFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''CercaButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CercaButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''InsertValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InsertValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary
        
        '''<summary>
        '''EditValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary
        
        '''<summary>
        '''EnnupleListView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnupleListView As Global.System.Web.UI.WebControls.ListView
        
        '''<summary>
        '''EnnupleObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnupleObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''PrioritaObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PrioritaObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''RegimiObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegimiObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''EnnupleStatiObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnupleStatiObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''UnitaOperativeObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnitaOperativeObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''SistemiRichiedentiObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SistemiRichiedentiObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''GruppiPrestazioniObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GruppiPrestazioniObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''GruppiUtentiObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GruppiUtentiObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''EnnuplaDetail_IdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_IdHiddenField As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''EnnuplaDetail_NotCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_NotCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_StatoDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_StatoDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EnnuplaDetail_DescrizioneTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_DescrizioneTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''EnnuplaDetail_NoteTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_NoteTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''EnnuplaDetail_GruppoUtentiDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_GruppoUtentiDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EnnuplaDetail_GruppiPrestazioniDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_GruppiPrestazioniDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EnnuplaDetail_OraInizioTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_OraInizioTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''EnnuplaDetail_OraFineTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_OraFineTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''EnnuplaDetail_LunediCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_LunediCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_MartediCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_MartediCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_MercolediCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_MercolediCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_GiovediCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_GiovediCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_VenerdiCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_VenerdiCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_SabatoCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_SabatoCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_DomenicaCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_DomenicaCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''EnnuplaDetail_UnitaOperativaDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_UnitaOperativaDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EnnuplaDetail_SistemaRichiedenteDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_SistemaRichiedenteDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EnnuplaDetail_RegimeDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_RegimeDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EnnuplaDetail_PrioritaDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnnuplaDetail_PrioritaDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''SaveButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
