'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.OrderEntry.Admin
    
    Partial Public Class ListaSistemi
        
        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''filterPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterPanel As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''CodiceDescrizioneFiltroTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CodiceDescrizioneFiltroTextBox As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''AziendaFiltroDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AziendaFiltroDropDownList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''EroganteCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EroganteCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''RichiedenteCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RichiedenteCheckBox As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''AttivoDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AttivoDropDown As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''CancellazionePostInoltroDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancellazionePostInoltroDropDown As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''CancellazionePostInCaricoDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancellazionePostInCaricoDropDown As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''CercaButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CercaButton As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''labelCodiceDatoAccessorio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelCodiceDatoAccessorio As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''AziendeObjectDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AziendeObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
