CREATE TABLE [codifiche].[FarmaDitteProduttrici] (
    [Id]                UNIQUEIDENTIFIER CONSTRAINT [DF_FarmaDitteProduttrici_Id] DEFAULT (newsequentialid()) NOT NULL,
    [CodiceDitta]       VARCHAR (16)     NOT NULL,
    [Divisione]         VARCHAR (2)      NULL,
    [RagioneSociale]    VARCHAR (30)     NULL,
    [CodiceFiscale]     VARCHAR (16)     NULL,
    [IndirizzoInternet] VARCHAR (50)     NULL,
    [TipoIndirizzo1]    VARCHAR (25)     NULL,
    [Indirizzo1]        VARCHAR (30)     NULL,
    [CAP1]              VARCHAR (5)      NULL,
    [Citta1]            VARCHAR (25)     NULL,
    [Provincia1]        CHAR (2)         NULL,
    [Tel1]              VARCHAR (15)     NULL,
    [Fax1]              VARCHAR (15)     NULL,
    [Email1]            VARCHAR (30)     NULL,
    [TipoIndirizzo2]    VARCHAR (25)     NULL,
    [Indirizzo2]        VARCHAR (30)     NULL,
    [CAP2]              VARCHAR (5)      NULL,
    [Citta2]            VARCHAR (25)     NULL,
    [Provincia2]        CHAR (2)         NULL,
    [Tel2]              VARCHAR (15)     NULL,
    [Fax2]              VARCHAR (15)     NULL,
    [Email2]            VARCHAR (30)     NULL,
    [TipoIndirizzo3]    VARCHAR (25)     NULL,
    [Indirizzo3]        VARCHAR (30)     NULL,
    [CAP3]              VARCHAR (5)      NULL,
    [Citta3]            VARCHAR (25)     NULL,
    [Provincia3]        CHAR (2)         NULL,
    [Tel3]              VARCHAR (15)     NULL,
    [Fax3]              VARCHAR (15)     NULL,
    [Email3]            VARCHAR (30)     NULL,
    [AssInde]           CHAR (1)         NULL,
    [AderenteDal]       DATE             NULL,
    [AderenteAl]        DATE             NULL,
    [Farmaindustria]    CHAR (1)         NULL,
    [Nazione]           CHAR (3)         NULL,
    [DataInserimento]   DATETIME         CONSTRAINT [DF_FarmaDitteProduttrici_DataInserimento] DEFAULT (getutcdate()) NOT NULL,
    [DataModifica]      DATETIME         CONSTRAINT [DF_FarmaDitteProduttrici_DataModifica] DEFAULT (getutcdate()) NOT NULL,
    [UtenteInserimento] VARCHAR (128)    CONSTRAINT [DF_FarmaDitteProduttrici_UtenteInserimento] DEFAULT (suser_sname()) NOT NULL,
    [UtenteModifica]    VARCHAR (128)    CONSTRAINT [DF_FarmaDitteProduttrici_UtenteModifica] DEFAULT (suser_sname()) NOT NULL,
    CONSTRAINT [PK_DitteProduttrici] PRIMARY KEY CLUSTERED ([Id] ASC)
);

