'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UtentiSQLAggiungiLista

	'''<summary>
	'''LabelError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''LabelTitolo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LabelTitolo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pannelloFiltri control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pannelloFiltri As Global.System.Web.UI.HtmlControls.HtmlTable

	'''<summary>
	'''txtFiltriUtente control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFiltriUtente As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''butFiltriRicerca control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butFiltriRicerca As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''butConfermaTop control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butConfermaTop As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''butAnnullaTop control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butAnnullaTop As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''gvLista control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvLista As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''butConferma control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butConferma As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''butAnnulla control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butAnnulla As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''odsLista control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsLista As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
