'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.OrderEntry.User
    
    Partial Public Class ComposizioneOrdineMethods
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As DI.OrderEntry.User.Site
            Get
                Return CType(MyBase.Master,DI.OrderEntry.User.Site)
            End Get
        End Property
    End Class
End Namespace
