'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.OrderEntry.Admin
    
    Partial Public Class OrderEntry
        
        '''<summary>
        '''OrderEntryContentPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrderEntryContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As DI.OrderEntry.Admin.Site
            Get
                Return CType(MyBase.Master,DI.OrderEntry.Admin.Site)
            End Get
        End Property
    End Class
End Namespace
