'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RicoveriRiassociazioneSACPazientiLista
    
    '''<summary>
    '''LabelError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pannelloFiltri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pannelloFiltri As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''CognomeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CognomeTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NomeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NomeTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OccultatoRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OccultatoRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''CodiceFiscaleTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CodiceFiscaleTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''IdSacTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IdSacTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AnnoNascitaTextBoxRegularExpressionValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnnoNascitaTextBoxRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''AnnoNascitaTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnnoNascitaTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ProvenienzaTexttBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProvenienzaTexttBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RicercaButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RicercaButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''StatoDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatoDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''IdProvenienzaTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IdProvenienzaTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''butAnnulla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butAnnulla As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PazientiGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PazientiGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PazientiListaObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PazientiListaObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
