'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Asmn.Sac.Msg.DataAccess.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il {0} è già stato cancellato virtualmente!.
        '''</summary>
        Friend ReadOnly Property ExceptionCancellatoVirtualmente() As String
            Get
                Return ResourceManager.GetString("ExceptionCancellatoVirtualmente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errore di data sequenza! Il {0} sul database ha una data sequenza maggiore di quello corrente..
        '''</summary>
        Friend ReadOnly Property ExceptionDataSequenza() As String
            Get
                Return ResourceManager.GetString("ExceptionDataSequenza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errore di dati già presenti! I {0} è già nel database con IdProvenienza+Provenienza uguale..
        '''</summary>
        Friend ReadOnly Property ExceptionDatiGiaPresenti() As String
            Get
                Return ResourceManager.GetString("ExceptionDatiGiaPresenti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I dati del {0} non corrispondono ai vincoli! {1}.
        '''</summary>
        Friend ReadOnly Property ExceptionDatiInconsistenti() As String
            Get
                Return ResourceManager.GetString("ExceptionDatiInconsistenti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errore di dati non trovati! Non è stato trovato il {0} durante la lettura per IdProvenienza+Provenienza..
        '''</summary>
        Friend ReadOnly Property ExceptionDatiNonTrovati() As String
            Get
                Return ResourceManager.GetString("ExceptionDatiNonTrovati", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errore di query dati {0}; la Stored Precedure ha ritornato RowCount=0!.
        '''</summary>
        Friend ReadOnly Property ExceptionRowCountZero() As String
            Get
                Return ResourceManager.GetString("ExceptionRowCountZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La sincronizzazione al servizio {0} con la chiave {1} non è stata acquisita! .
        '''</summary>
        Friend ReadOnly Property ExceptionSincronizzazione() As String
            Get
                Return ResourceManager.GetString("ExceptionSincronizzazione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il {0} è un sinonimo e non è modificabile! .
        '''</summary>
        Friend ReadOnly Property ExceptionSinonimo() As String
            Get
                Return ResourceManager.GetString("ExceptionSinonimo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
