'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization
<Assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1", ClrNamespace:="EroganteGenericoTypes")> 

Namespace EroganteGenericoTypes
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CodiceDescrizioneType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class CodiceDescrizioneType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodiceField As String
        
        Private DescrizioneField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                Me.CodiceField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                Me.DescrizioneField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ConsensiType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1", ItemName:="Consenso")>  _
    Public Class ConsensiType
        Inherits System.Collections.Generic.List(Of EroganteGenericoTypes.ConsensoType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsensoType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class ConsensoType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private TipoField As String
        
        Private ValoreField As Boolean
        
        Private DataField As Date
        
        Private OperatoreField As EroganteGenericoTypes.OperatoreType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Tipo() As String
            Get
                Return Me.TipoField
            End Get
            Set
                Me.TipoField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Valore() As Boolean
            Get
                Return Me.ValoreField
            End Get
            Set
                Me.ValoreField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property Data() As Date
            Get
                Return Me.DataField
            End Get
            Set
                Me.DataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Operatore() As EroganteGenericoTypes.OperatoreType
            Get
                Return Me.OperatoreField
            End Get
            Set
                Me.OperatoreField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OperatoreType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class OperatoreType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As String
        
        Private CognomeField As String
        
        Private NomeField As String
        
        Private CodiceFiscaleField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property ID() As String
            Get
                Return Me.IDField
            End Get
            Set
                Me.IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Cognome() As String
            Get
                Return Me.CognomeField
            End Get
            Set
                Me.CognomeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                Me.NomeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property CodiceFiscale() As String
            Get
                Return Me.CodiceFiscaleField
            End Get
            Set
                Me.CodiceFiscaleField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="DatiAggiuntiviType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1", ItemName:="DatoAggiuntivo")>  _
    Public Class DatiAggiuntiviType
        Inherits System.Collections.Generic.List(Of EroganteGenericoTypes.DatoNomeValoreType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DatoNomeValoreType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class DatoNomeValoreType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As String
        
        Private NomeField As String
        
        Private TipoDatoField As String
        
        Private TipoContenutoField As String
        
        Private ValoreDatoField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                Me.IdField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                Me.NomeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property TipoDato() As String
            Get
                Return Me.TipoDatoField
            End Get
            Set
                Me.TipoDatoField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property TipoContenuto() As String
            Get
                Return Me.TipoContenutoField
            End Get
            Set
                Me.TipoContenutoField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=4)>  _
        Public Property ValoreDato() As String
            Get
                Return Me.ValoreDatoField
            End Get
            Set
                Me.ValoreDatoField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="DatiPersistentiType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1", ItemName:="DatoPersistente")>  _
    Public Class DatiPersistentiType
        Inherits System.Collections.Generic.List(Of EroganteGenericoTypes.DatoNomeValoreType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InstradamentoSistemaType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class InstradamentoSistemaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private AziendaField As String
        
        Private SistemaField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Azienda() As String
            Get
                Return Me.AziendaField
            End Get
            Set
                Me.AziendaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Sistema() As String
            Get
                Return Me.SistemaField
            End Get
            Set
                Me.SistemaField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InstradamentoType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class InstradamentoType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private RichiedenteField As EroganteGenericoTypes.InstradamentoSistemaType
        
        Private EroganteField As EroganteGenericoTypes.InstradamentoSistemaType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Richiedente() As EroganteGenericoTypes.InstradamentoSistemaType
            Get
                Return Me.RichiedenteField
            End Get
            Set
                Me.RichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
        Public Property Erogante() As EroganteGenericoTypes.InstradamentoSistemaType
            Get
                Return Me.EroganteField
            End Get
            Set
                Me.EroganteField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OperazioneRigaRichiestaOrderEntryEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum OperazioneRigaRichiestaOrderEntryEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [IS] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MD = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CA = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OperazioneTestataRichiestaOrderEntryEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum OperazioneTestataRichiestaOrderEntryEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HD = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [IN] = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SR = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MD = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CA = 4
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PazienteType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class PazienteType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdRichiedenteField As String
        
        Private IdSacField As String
        
        Private AnagraficaCodiceField As String
        
        Private AnagraficaNomeField As String
        
        Private CodiceFiscaleField As String
        
        Private CognomeField As String
        
        Private NomeField As String
        
        Private DataNascitaField As System.Nullable(Of Date)
        
        Private ComuneNascitaField As String
        
        Private CodiceIstatComuneNascitaField As String
        
        Private SessoField As String
        
        Private IndirizzoResidenzaField As String
        
        Private ComuneResidenzaField As String
        
        Private CodiceIstatComuneResidenzaField As String
        
        Private CapResidenzaField As String
        
        Private NazionalitaField As String
        
        Private CodiceIstatNazionalitaField As String
        
        Private CittadinanzaField As String
        
        Private CodiceIstatCittadinanzaField As String
        
        Private DataModificaField As Date
        
        Private TesseraSanitariaField As String
        
        Private CodiceUslField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IdRichiedente() As String
            Get
                Return Me.IdRichiedenteField
            End Get
            Set
                Me.IdRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IdSac() As String
            Get
                Return Me.IdSacField
            End Get
            Set
                Me.IdSacField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property AnagraficaCodice() As String
            Get
                Return Me.AnagraficaCodiceField
            End Get
            Set
                Me.AnagraficaCodiceField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property AnagraficaNome() As String
            Get
                Return Me.AnagraficaNomeField
            End Get
            Set
                Me.AnagraficaNomeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=4)>  _
        Public Property CodiceFiscale() As String
            Get
                Return Me.CodiceFiscaleField
            End Get
            Set
                Me.CodiceFiscaleField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Cognome() As String
            Get
                Return Me.CognomeField
            End Get
            Set
                Me.CognomeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                Me.NomeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public Property DataNascita() As System.Nullable(Of Date)
            Get
                Return Me.DataNascitaField
            End Get
            Set
                Me.DataNascitaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property ComuneNascita() As String
            Get
                Return Me.ComuneNascitaField
            End Get
            Set
                Me.ComuneNascitaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property CodiceIstatComuneNascita() As String
            Get
                Return Me.CodiceIstatComuneNascitaField
            End Get
            Set
                Me.CodiceIstatComuneNascitaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Sesso() As String
            Get
                Return Me.SessoField
            End Get
            Set
                Me.SessoField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property IndirizzoResidenza() As String
            Get
                Return Me.IndirizzoResidenzaField
            End Get
            Set
                Me.IndirizzoResidenzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property ComuneResidenza() As String
            Get
                Return Me.ComuneResidenzaField
            End Get
            Set
                Me.ComuneResidenzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property CodiceIstatComuneResidenza() As String
            Get
                Return Me.CodiceIstatComuneResidenzaField
            End Get
            Set
                Me.CodiceIstatComuneResidenzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property CapResidenza() As String
            Get
                Return Me.CapResidenzaField
            End Get
            Set
                Me.CapResidenzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property Nazionalita() As String
            Get
                Return Me.NazionalitaField
            End Get
            Set
                Me.NazionalitaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property CodiceIstatNazionalita() As String
            Get
                Return Me.CodiceIstatNazionalitaField
            End Get
            Set
                Me.CodiceIstatNazionalitaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property Cittadinanza() As String
            Get
                Return Me.CittadinanzaField
            End Get
            Set
                Me.CittadinanzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property CodiceIstatCittadinanza() As String
            Get
                Return Me.CodiceIstatCittadinanzaField
            End Get
            Set
                Me.CodiceIstatCittadinanzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=19)>  _
        Public Property DataModifica() As Date
            Get
                Return Me.DataModificaField
            End Get
            Set
                Me.DataModificaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=20)>  _
        Public Property TesseraSanitaria() As String
            Get
                Return Me.TesseraSanitariaField
            End Get
            Set
                Me.TesseraSanitariaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property CodiceUsl() As String
            Get
                Return Me.CodiceUslField
            End Get
            Set
                Me.CodiceUslField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PrestazioneType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class PrestazioneType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodiceField As String
        
        Private DescrizioneField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Codice() As String
            Get
                Return Me.CodiceField
            End Get
            Set
                Me.CodiceField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Descrizione() As String
            Get
                Return Me.DescrizioneField
            End Get
            Set
                Me.DescrizioneField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PrioritaEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum PrioritaEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        P = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        O = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UD = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        U = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        U2 = 4
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RegimeEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum RegimeEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LP = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AMB = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DSA = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RO = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DH = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PS = 5
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RigaErogataType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class RigaErogataType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdRigaOrderEntryField As String
        
        Private StatoOrderEntryField As String
        
        Private IdRigaRichiedenteField As String
        
        Private IdRigaEroganteField As String
        
        Private StatoEroganteField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Private DataField As System.Nullable(Of Date)
        
        Private OperatoreField As EroganteGenericoTypes.OperatoreType
        
        Private PrestazioneField As EroganteGenericoTypes.PrestazioneType
        
        Private ConsensiField As EroganteGenericoTypes.ConsensiType
        
        Private DatiAggiuntiviField As EroganteGenericoTypes.DatiAggiuntiviType
        
        Private VersioneField As EroganteGenericoTypes.VersioneType
        
        Private TipoOperazioneField As EroganteGenericoTypes.TipoRigaOperazioneType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IdRigaOrderEntry() As String
            Get
                Return Me.IdRigaOrderEntryField
            End Get
            Set
                Me.IdRigaOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property StatoOrderEntry() As String
            Get
                Return Me.StatoOrderEntryField
            End Get
            Set
                Me.StatoOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property IdRigaRichiedente() As String
            Get
                Return Me.IdRigaRichiedenteField
            End Get
            Set
                Me.IdRigaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property IdRigaErogante() As String
            Get
                Return Me.IdRigaEroganteField
            End Get
            Set
                Me.IdRigaEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=4)>  _
        Public Property StatoErogante() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.StatoEroganteField
            End Get
            Set
                Me.StatoEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property Data() As System.Nullable(Of Date)
            Get
                Return Me.DataField
            End Get
            Set
                Me.DataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Operatore() As EroganteGenericoTypes.OperatoreType
            Get
                Return Me.OperatoreField
            End Get
            Set
                Me.OperatoreField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=7)>  _
        Public Property Prestazione() As EroganteGenericoTypes.PrestazioneType
            Get
                Return Me.PrestazioneField
            End Get
            Set
                Me.PrestazioneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property Consensi() As EroganteGenericoTypes.ConsensiType
            Get
                Return Me.ConsensiField
            End Get
            Set
                Me.ConsensiField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property DatiAggiuntivi() As EroganteGenericoTypes.DatiAggiuntiviType
            Get
                Return Me.DatiAggiuntiviField
            End Get
            Set
                Me.DatiAggiuntiviField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Versione() As EroganteGenericoTypes.VersioneType
            Get
                Return Me.VersioneField
            End Get
            Set
                Me.VersioneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
        Public Property TipoOperazione() As EroganteGenericoTypes.TipoRigaOperazioneType
            Get
                Return Me.TipoOperazioneField
            End Get
            Set
                Me.TipoOperazioneField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VersioneType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class VersioneType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private DataSequenzaField As Date
        
        Private NumeroSequenzaField As Integer
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataSequenza() As Date
            Get
                Return Me.DataSequenzaField
            End Get
            Set
                Me.DataSequenzaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroSequenza() As Integer
            Get
                Return Me.NumeroSequenzaField
            End Get
            Set
                Me.NumeroSequenzaField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoRigaOperazioneType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum TipoRigaOperazioneType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Inserisce = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Modifica = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Rimuove = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RigaRichiestaType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class RigaRichiestaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdRigaOrderEntryField As String
        
        Private OperazioneOrderEntryField As String
        
        Private IdRigaRichiedenteField As String
        
        Private IdRigaEroganteField As String
        
        Private IdRichiestaEroganteField As String
        
        Private PrestazioneField As EroganteGenericoTypes.PrestazioneType
        
        Private ConsensiField As EroganteGenericoTypes.ConsensiType
        
        Private DatiAggiuntiviField As EroganteGenericoTypes.DatiAggiuntiviType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IdRigaOrderEntry() As String
            Get
                Return Me.IdRigaOrderEntryField
            End Get
            Set
                Me.IdRigaOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OperazioneOrderEntry() As String
            Get
                Return Me.OperazioneOrderEntryField
            End Get
            Set
                Me.OperazioneOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property IdRigaRichiedente() As String
            Get
                Return Me.IdRigaRichiedenteField
            End Get
            Set
                Me.IdRigaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property IdRigaErogante() As String
            Get
                Return Me.IdRigaEroganteField
            End Get
            Set
                Me.IdRigaEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property IdRichiestaErogante() As String
            Get
                Return Me.IdRichiestaEroganteField
            End Get
            Set
                Me.IdRichiestaEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=5)>  _
        Public Property Prestazione() As EroganteGenericoTypes.PrestazioneType
            Get
                Return Me.PrestazioneField
            End Get
            Set
                Me.PrestazioneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Consensi() As EroganteGenericoTypes.ConsensiType
            Get
                Return Me.ConsensiField
            End Get
            Set
                Me.ConsensiField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property DatiAggiuntivi() As EroganteGenericoTypes.DatiAggiuntiviType
            Get
                Return Me.DatiAggiuntiviField
            End Get
            Set
                Me.DatiAggiuntiviField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="RigheErogateType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1", ItemName:="RigaErogata")>  _
    Public Class RigheErogateType
        Inherits System.Collections.Generic.List(Of EroganteGenericoTypes.RigaErogataType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="RigheRichiesteType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1", ItemName:="RigaRichiesta")>  _
    Public Class RigheRichiesteType
        Inherits System.Collections.Generic.List(Of EroganteGenericoTypes.RigaRichiestaType)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SistemaType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class SistemaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private AziendaField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Private SistemaField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Azienda() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.AziendaField
            End Get
            Set
                Me.AziendaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Sistema() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.SistemaField
            End Get
            Set
                Me.SistemaField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StatoEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum StatoEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AA = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AR = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AE = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StatoRigaErogataOrderEntryEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum StatoRigaErogataOrderEntryEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IC = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IP = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CM = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CA = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StatoTestataErogatoOrderEntryEnum", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum StatoTestataErogatoOrderEntryEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AA = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AR = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AE = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SE = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IC = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IP = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CM = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CA = 7
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StrutturaType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class StrutturaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private AziendaField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Private UnitaOperativaField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property Azienda() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.AziendaField
            End Get
            Set
                Me.AziendaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property UnitaOperativa() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.UnitaOperativaField
            End Get
            Set
                Me.UnitaOperativaField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RichiestaType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class RichiestaType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdRichiestaOrderEntryField As String
        
        Private DataVersioneField As System.Nullable(Of Date)
        
        Private IdRichiestaRichiedenteField As String
        
        Private SistemaRichiedenteField As EroganteGenericoTypes.SistemaType
        
        Private UnitaOperativaRichiedenteField As EroganteGenericoTypes.StrutturaType
        
        Private SistemaEroganteField As EroganteGenericoTypes.SistemaType
        
        Private NumeroNosologicoField As String
        
        Private RegimeField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Private DataRichiestaField As Date
        
        Private OperazioneOrderEntryField As String
        
        Private DataPrenotazioneField As System.Nullable(Of Date)
        
        Private OperatoreField As EroganteGenericoTypes.OperatoreType
        
        Private PrioritaField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Private PazienteField As EroganteGenericoTypes.PazienteType
        
        Private NoteField As String
        
        Private ConsensiField As EroganteGenericoTypes.ConsensiType
        
        Private DatiAggiuntiviField As EroganteGenericoTypes.DatiAggiuntiviType
        
        Private DatiPersistentiField As EroganteGenericoTypes.DatiPersistentiType
        
        Private RigheRichiesteField As EroganteGenericoTypes.RigheRichiesteType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property IdRichiestaOrderEntry() As String
            Get
                Return Me.IdRichiestaOrderEntryField
            End Get
            Set
                Me.IdRichiestaOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property DataVersione() As System.Nullable(Of Date)
            Get
                Return Me.DataVersioneField
            End Get
            Set
                Me.DataVersioneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=2)>  _
        Public Property IdRichiestaRichiedente() As String
            Get
                Return Me.IdRichiestaRichiedenteField
            End Get
            Set
                Me.IdRichiestaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=3)>  _
        Public Property SistemaRichiedente() As EroganteGenericoTypes.SistemaType
            Get
                Return Me.SistemaRichiedenteField
            End Get
            Set
                Me.SistemaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=4)>  _
        Public Property UnitaOperativaRichiedente() As EroganteGenericoTypes.StrutturaType
            Get
                Return Me.UnitaOperativaRichiedenteField
            End Get
            Set
                Me.UnitaOperativaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=5)>  _
        Public Property SistemaErogante() As EroganteGenericoTypes.SistemaType
            Get
                Return Me.SistemaEroganteField
            End Get
            Set
                Me.SistemaEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property NumeroNosologico() As String
            Get
                Return Me.NumeroNosologicoField
            End Get
            Set
                Me.NumeroNosologicoField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Regime() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.RegimeField
            End Get
            Set
                Me.RegimeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property DataRichiesta() As Date
            Get
                Return Me.DataRichiestaField
            End Get
            Set
                Me.DataRichiestaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=9)>  _
        Public Property OperazioneOrderEntry() As String
            Get
                Return Me.OperazioneOrderEntryField
            End Get
            Set
                Me.OperazioneOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
        Public Property DataPrenotazione() As System.Nullable(Of Date)
            Get
                Return Me.DataPrenotazioneField
            End Get
            Set
                Me.DataPrenotazioneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property Operatore() As EroganteGenericoTypes.OperatoreType
            Get
                Return Me.OperatoreField
            End Get
            Set
                Me.OperatoreField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property Priorita() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.PrioritaField
            End Get
            Set
                Me.PrioritaField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property Paziente() As EroganteGenericoTypes.PazienteType
            Get
                Return Me.PazienteField
            End Get
            Set
                Me.PazienteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Note() As String
            Get
                Return Me.NoteField
            End Get
            Set
                Me.NoteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property Consensi() As EroganteGenericoTypes.ConsensiType
            Get
                Return Me.ConsensiField
            End Get
            Set
                Me.ConsensiField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property DatiAggiuntivi() As EroganteGenericoTypes.DatiAggiuntiviType
            Get
                Return Me.DatiAggiuntiviField
            End Get
            Set
                Me.DatiAggiuntiviField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property DatiPersistenti() As EroganteGenericoTypes.DatiPersistentiType
            Get
                Return Me.DatiPersistentiField
            End Get
            Set
                Me.DatiPersistentiField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=18)>  _
        Public Property RigheRichieste() As EroganteGenericoTypes.RigheRichiesteType
            Get
                Return Me.RigheRichiesteField
            End Get
            Set
                Me.RigheRichiesteField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TestataStatoType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Partial Public Class TestataStatoType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdRichiestaOrderEntryField As String
        
        Private StatoOrderEntryField As String
        
        Private IdRichiestaRichiedenteField As String
        
        Private SistemaRichiedenteField As EroganteGenericoTypes.SistemaType
        
        Private IdRichiestaEroganteField As String
        
        Private SistemaEroganteField As EroganteGenericoTypes.SistemaType
        
        Private StatoEroganteField As EroganteGenericoTypes.CodiceDescrizioneType
        
        Private DataField As System.Nullable(Of Date)
        
        Private DataPrenotazioneField As Date
        
        Private OperatoreField As EroganteGenericoTypes.OperatoreType
        
        Private PazienteField As EroganteGenericoTypes.PazienteType
        
        Private NoteField As String
        
        Private ConsensiField As EroganteGenericoTypes.ConsensiType
        
        Private DatiAggiuntiviField As EroganteGenericoTypes.DatiAggiuntiviType
        
        Private DatiPersistentiField As EroganteGenericoTypes.DatiPersistentiType
        
        Private RigheErogateField As EroganteGenericoTypes.RigheErogateType
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IdRichiestaOrderEntry() As String
            Get
                Return Me.IdRichiestaOrderEntryField
            End Get
            Set
                Me.IdRichiestaOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StatoOrderEntry() As String
            Get
                Return Me.StatoOrderEntryField
            End Get
            Set
                Me.StatoOrderEntryField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property IdRichiestaRichiedente() As String
            Get
                Return Me.IdRichiestaRichiedenteField
            End Get
            Set
                Me.IdRichiestaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property SistemaRichiedente() As EroganteGenericoTypes.SistemaType
            Get
                Return Me.SistemaRichiedenteField
            End Get
            Set
                Me.SistemaRichiedenteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property IdRichiestaErogante() As String
            Get
                Return Me.IdRichiestaEroganteField
            End Get
            Set
                Me.IdRichiestaEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=5)>  _
        Public Property SistemaErogante() As EroganteGenericoTypes.SistemaType
            Get
                Return Me.SistemaEroganteField
            End Get
            Set
                Me.SistemaEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property StatoErogante() As EroganteGenericoTypes.CodiceDescrizioneType
            Get
                Return Me.StatoEroganteField
            End Get
            Set
                Me.StatoEroganteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public Property Data() As System.Nullable(Of Date)
            Get
                Return Me.DataField
            End Get
            Set
                Me.DataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public Property DataPrenotazione() As Date
            Get
                Return Me.DataPrenotazioneField
            End Get
            Set
                Me.DataPrenotazioneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property Operatore() As EroganteGenericoTypes.OperatoreType
            Get
                Return Me.OperatoreField
            End Get
            Set
                Me.OperatoreField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Paziente() As EroganteGenericoTypes.PazienteType
            Get
                Return Me.PazienteField
            End Get
            Set
                Me.PazienteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property Note() As String
            Get
                Return Me.NoteField
            End Get
            Set
                Me.NoteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property Consensi() As EroganteGenericoTypes.ConsensiType
            Get
                Return Me.ConsensiField
            End Get
            Set
                Me.ConsensiField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property DatiAggiuntivi() As EroganteGenericoTypes.DatiAggiuntiviType
            Get
                Return Me.DatiAggiuntiviField
            End Get
            Set
                Me.DatiAggiuntiviField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property DatiPersistenti() As EroganteGenericoTypes.DatiPersistentiType
            Get
                Return Me.DatiPersistentiField
            End Get
            Set
                Me.DatiPersistentiField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property RigheErogate() As EroganteGenericoTypes.RigheErogateType
            Get
                Return Me.RigheErogateField
            End Get
            Set
                Me.RigheErogateField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoOperazioneType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum TipoOperazioneType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Completo = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Incrementale = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TipoStatoType", [Namespace]:="http://schemas.progel.it/WCF/OE/EroganteGenericoTypes/1.1")>  _
    Public Enum TipoStatoType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RR = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OSU = 1
    End Enum
End Namespace
