CREATE LOGIN [DEV_SCHEMA_COMPARE]
    WITH PASSWORD = N'$biasscxofo<ds|akYdDvwvkmsFT7_&#$!~<vo{zo%ib6mh|', SID = 0x89FA7E4BB4AE86499553A6F4ADD3FFA0, DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

