'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DI.OrderEntry.User
    
    Partial Public Class DatiAccessori
        
        '''<summary>
        '''divErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divErrorMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''UpdateProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateProgress As Global.System.Web.UI.UpdateProgress
        
        '''<summary>
        '''UcWizard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UcWizard As Global.UcWizard
        
        '''<summary>
        '''ucDettaglioPaziente2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucDettaglioPaziente2 As Global.ucDettaglioPaziente2
        
        '''<summary>
        '''updDatiAccessori control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents updDatiAccessori As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''dtGruppi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtGruppi As Global.System.Web.UI.WebControls.DataList
        
        '''<summary>
        '''odsGruppi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsGruppi As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''lblErroriCompilazione control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErroriCompilazione As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''btnModalAvanti control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnModalAvanti As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''timer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents timer As Global.System.Web.UI.Timer
        
        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As DI.OrderEntry.User.Site
            Get
                Return CType(MyBase.Master,DI.OrderEntry.User.Site)
            End Get
        End Property
    End Class
End Namespace
