'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RiepilogoDatiAccessori
    
    '''<summary>
    '''divErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErrorMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblIdRichiesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdRichiesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblRegime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegime As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPriorita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriorita As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDataPrenotazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataPrenotazione As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DatiAccessoriIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatiAccessoriIcon As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gvDatiAccessoriTestata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDatiAccessoriTestata As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''odsDatiAccessoriTestata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDatiAccessoriTestata As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''rptDatiAccessoriErogante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDatiAccessoriErogante As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''odsDatiAccessoriErogante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDatiAccessoriErogante As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
